spring.application.name=profile-example
server.port = 8080
#.servlet.context-path=/location-updator
spring.profiles.active= prod
# ===============================
# MYSQL CONNECTION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/27th_oct_batch
spring.datasource.username=root
spring.datasource.password=SP25@hit
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect