spring.application.name=search-product-redis
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/sample_db
spring.datasource.username=root
spring.datasource.password=SP25@hit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.data.redis.host=frank-bream-124861.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAee9AAIgcDI2YWIzZTEyNjQ2Nzc0N2NmYWViOGZkY2RiOTY2MzJlZg
spring.data.redis.ssl.enabled=true

spring.cache.type=redis

# OPTIONAL LOGS
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG