spring.application.name=KafkaOrder

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/kafka_order
spring.datasource.username=root
spring.datasource.password=SP25@hit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Kafka Cluster
spring.kafka.bootstrap-servers=localhost:9092

# Key Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value Serializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.producer.acks=all