spring.application.name=Employee-Management-RestAPI
server.port = 8080
spring.datasource.url=jdbc:mysql://localhost:3306/employeerest
spring.datasource.username=root
spring.datasource.password=SP25@hit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true